steps:
  - template: ../steps/prepare-environment.yml
  - template: ../steps/install-dependencies.yml
  - template: ../steps/build-packages.yml
  - script: yarn lint:format
    displayName: "Lint format"
  - script: yarn lint:packages
    displayName: "Lint packages"
    condition: succeededOrFailed()
