steps:
  - template: ../steps/prepare-environment.yml
  - template: ../steps/install-dependencies.yml
  - template: ../steps/build-packages.yml
  - script: yarn format:check
    displayName: "Check formatting"
  - script: yarn lint
    displayName: "Lint"
